name: errorgap
description: Flutter notifier for Errorgap error tracking.
version: 0.1.0
homepage: https://gitlab.jgrubbs.net/jGRUBBS/errorgap-flutter
repository: https://gitlab.jgrubbs.net/jGRUBBS/errorgap-flutter
issue_tracker: https://gitlab.jgrubbs.net/jGRUBBS/errorgap-flutter/-/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.2.0

dev_dependencies:
  test: ^1.25.0
  lints: ^4.0.0
